maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 40)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 30)
basic.pause(1800)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 40)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 30)
basic.pause(1800)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 40)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 30)
basic.pause(1800)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 40)
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
basic.forever(function () {
	
})
